include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'example/**'

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - use_super_parameters
