name: status_alert
description: Display Apple system-like self-hiding status alerts. It is well suited for notifying user without interrupting user flow.
version: 2.0.0
homepage: https://github.com/yako-dev/flutter-status-alert

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: SFNS
      fonts:
        - asset: assets/fonts/SFNS.ttf
